Dodati Kolokvijumi iz MAT2 u I Godina/Letnji Semestar
Produktivna-grupa/PMFKG pull request #10
Opened 2024-06-15 20:13 UTC by zarkyzaric

2024-06-16 07:43 UTC, TodorovicSrdjan approved these changes

2024-06-16 07:54 UTC, TodorovicSrdjan requested changes
@zarkyzaric hvala na doprinosu projektu 😃

Da li možeš da ukloniš postavke? Zaključak nas maintainer-a nakon razgovora sa profesorima oko ove inicijative je bio da je najbolje da ovo bude samo repo rešenja i beleški, tj. materijala koji su studenti kreirali. Da bi postavke (kao i drugi materijal kreiran od strane nastavnog osoblja) bile javno dostupne, potrebno je odobrenje predmetnog profesora.

2024-06-27 08:33 UTC, zarkyzaric commented
@TodorovicSrdjan Nema na čemu.

Znači ako nije javno dostupno na IMI sajtu, ne može da bude ni IMIOER? Dakle ne postoji rešenje koje bi dozvolilo javno razmenjivanje prethodnih kolokvijuma i ispita? 

Mislim da se u tome javlja jako paradoksalni problem, jer na primer profesor da ispit i neki učenici (nazovimo ih genijalcima za ove potrebe) mogu da zapamte ceo test napamet, prekucaju ga  i to razmene sa ostalim studentima, ili sa njihovim budućim brucošima ili ostalim nižim godinama. Kako bi profesori sprečili tako nešto, a i zašto?

Testovi će kružiti bez dozvole i sa dozvolom, ali mi nije najjasniji razlog zašto je to tolika tajna

2024-06-28 20:36 UTC, dr460r commented
> Znači ako nije javno dostupno na IMI sajtu, ne može da bude ni PMFKG? Dakle ne postoji rešenje koje bi dozvolilo javno razmenjivanje prethodnih kolokvijuma i ispita?
> 
> Mislim da se u tome javlja jako paradoksalni problem, jer na primer profesor da ispit i neki učenici (nazovimo ih genijalcima za ove potrebe) mogu da zapamte ceo test napamet, prekucaju ga i to razmene sa ostalim studentima, ili sa njihovim budućim brucošima ili ostalim nižim godinama. Kako bi profesori sprečili tako nešto, a i zašto?
> 
> Testovi će kružiti bez dozvole i sa dozvolom, ali mi nije najjasniji razlog zašto je to tolika tajna.

@zarkyzaric Zdravo! Mislim da ti je argument skroz na mestu. Međutim, razlozi su zapravo pravne prirode.

Naime, za vreme online nastave tokom korone donesena je sledeća [odluka dekana](https://imi.pmf.kg.ac.rs/oglasi/14093-odluka-dekana-o-nacinu-koriscenja-materijala-sa-predavanja-i-snimaka-predavanja) koja je zapravo rezultovala ovom praksom da se ne kače postavke i ostali materijali koje nisu kreirali studenti.

Što se tiče materijala koji je već javno dostupan na Moodle-u, ima smisla da on sme biti dodat i ovde, mada često se postavkama iz prethodnih godina naknadno ukloni javna vidljivost, pa u tom slučaju ne bi valjalo da ovde ostane pošto je javno.

Zato su za sada postavke javno dostupne jedino ukoliko ih asistent/profesor postavi negde kao javne, ili ako dobijemo dozvolu pa se onda nađe ovde.

2024-11-21 19:16 UTC, closed without merging